### ISSUE TITLE
Initiate quickstart python program

### ISSUE THREAD

**Issue by RyanFWebb** [clingen-data-model/vcep-tracker-generator#1]
[Python quickstart ](https://developers.google.com/sheets/api/quickstart/python)

**Comment by RyanFWebb** [comment]
Ready for review with @larrybabb.

**Comment by larrybabb** [comment]
@RyanFWebb please point me at something for me to review.

**Comment by RyanFWebb** [comment]
Posted here: [quickstart folder](https://github.com/clingen-data-model/vcep-tracker-generator/tree/main/quickstart)
